version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bank-db-postgres
    ports:
      - "5343:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=bankdb
    volumes:
      - C:/Users/ITdiakon/dev/Java4ka/diakon-bank/pg-data:/var/lib/postgresql/data