version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: diakon-bank-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=diakon
      - POSTGRES_PASSWORD=wWdSht5igiRqaG_l
      - POSTGRES_DB=diakonbank
    volumes:
      - ./db-data:/var/lib/postgresql/data

volumes:
  postgres-data:
