spring.application.name=bank-api-service
server.port=6666

spring.datasource.url=jdbc:postgresql://localhost:5432/bankdb
spring.datasource.username=postgres
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.webflux.webclient.connect-timeout=5000ms

logging.level.root=WARN
logging.level.com.diakonbank.bankapiservice=DEBUG
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN
logging.pattern.console=%m%n

logging.level.com.diakonbank.bankapi.service.client.BankApiClient=DEBUG
logging.level.org.springframework.web.reactive.function.client=TRACE
