spring.application.name=???
server.port=6666

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/bankdb
spring.datasource.username=???
spring.datasource.password=???
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# WebClient Configuration
spring.webflux.webclient.connect-timeout=5000ms

# Bank API Credentials
bank.client.id=???
bank.client.suffix=???
bank.client.secret=???
